run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
  skip-files:
    - ".*_generated.go$"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gocyclo
    - dupl
    - goconst
  disable:
    - lll
    - gomnd

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"
      - name: error-naming
        severity: warning
        disabled: false
      - name: receiver-naming
        severity: warning
        disabled: false

  gocyclo:
    min-complexity: 15

  errcheck:
    check-type-assertions: true
    check-blank: false

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gocyclo
        - errcheck
    - path: cmd/
      linters:
        - errcheck

  exclude-use-default: true
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
