.PHONY: help tidy seed run test test-race test-integration test-all test-coverage simple-coverage docker-up docker-down docker-build docker-run docker-seed docker-logs fmt lint check clean

help:
	@echo "Available targets:"
	@echo "  make tidy            - Tidy and vendor dependencies"
	@echo "  make seed            - Seed the database with data"
	@echo "  make run             - Run the app server"
	@echo "  make test            - Run unit tests only (no Docker required)"
	@echo "  make test-race       - Run unit tests with race detector"
	@echo "  make test-integration- Run integration tests (requires Docker)"
	@echo "  make test-all        - Run all tests: unit + integration (requires Docker)"
	@echo "  make test-coverage   - Run tests and show coverage report in browser"
	@echo "  make simple-coverage - Run tests and show coverage in situ"
	@echo "  make docker-up       - Start docker containers (DB only)"
	@echo "  make docker-down     - Stop docker containers"
	@echo "  make docker-build    - Build Docker image for the application"
	@echo "  make docker-run      - Start full stack (DB + API) with docker-compose"
	@echo "  make docker-seed     - Seed database in Docker containers"
	@echo "  make docker-logs     - Show logs from docker containers"
	@echo "  make fmt             - Format code with goimports and gofmt"
	@echo "  make lint            - Run golangci-lint"
	@echo "  make check           - Run fmt + lint + test (full validation)"
	@echo "  make clean           - Remove generated files (use after coverage report generation)"

tidy:
	@echo "executing tidy..."
	@go mod tidy && go mod vendor

seed :
	@echo "executing seed..."
	@go run cmd/seed/main.go

run :
	@echo "executing run..."
	@go run cmd/server/main.go
test :
	@echo "executing unit tests (no Docker required)..."
	@go test -v -count=1 ./... -coverprofile=coverage.out -covermode=atomic

test-race :
	@echo "executing unit tests with race detector..."
	@go test -v -count=1 -race ./... -coverprofile=coverage.out -covermode=atomic

test-integration :
	@echo "executing integration tests (requires Docker)..."
	@go test -tags=integration -v -count=1 ./... -timeout 10m

test-all :
	@echo "executing all tests: unit + integration (requires Docker)..."
	@go test -tags=integration -v -count=1 ./... -coverprofile=coverage.out -covermode=atomic -timeout 10m

test-coverage: test
	@echo "Executing coverage with report (remember to clean)..."
	@go tool cover -html=coverage.out

simple-coverage:
	@echo "Executing coverage in situ..."
	@go tool cover -func=coverage.out | tail -n 1

docker-up:
	@echo "Starting docker containers (DB only)..."
	@docker compose up -d postgres

docker-down:
	@echo "Stopping docker containers..."
	@docker compose down

docker-build:
	@echo "Building Docker image..."
	@docker build -t mytheresa-catalog:latest .

docker-run:
	@echo "Starting full stack (DB + API)..."
	@docker compose up -d

docker-logs:
	@echo "Showing docker logs..."
	@docker compose logs -f

docker-seed:
	@echo "Seeding database in Docker..."
	@for sql in sql/*.sql; do \
		echo "Executing $$sql..."; \
		docker compose exec -T postgres psql -U postgres -d challenge < "$$sql"; \
	done

fmt:
	@echo "Executing code formatter..."
	@goimports -w . || gofmt -w .

lint:
	@echo "Executing linters..."
	@golangci-lint run ./...

check: fmt lint test
	@echo "All checks passed :D (formatter + linter + test)"


clean:
	@echo "Cleaning autogenerated files..."
	@rm -f coverage.out
