.PHONY: help tidy seed run test test-race test-coverage simple-coverage docker-up docker-down clean

help:
	@echo "Available targets:"
	@echo "  make tidy            - Tidy and vendor dependencies"
	@echo "  make seed            - Seed the database with data"
	@echo "  make run             - Run the app server"
	@echo "  make test            - Run tests with coverage and without race"
	@echo "  make test-race       - Run tests with race"
	@echo "  make test-coverage   - Run tests and show coverage report in browser"
	@echo "  make simple-coverage - Run tests and show coverage in situ"
	@echo "  make docker-up       - Start docker containers"
	@echo "  make docker-down     - Stop docker containers"
	@echo "  make clean           - Remove generated files (use after coverage report generation)"

tidy:
	@echo "excecuting tidy..."
	@go mod tidy && go mod vendor

seed :
	@echo "excecuting seed..."
	@go run cmd/seed/main.go

run :
	@echo "excecuting run..."
	@go run cmd/server/main.go
test :
	@echo "executing test without race..."
	@go test -v -count=1 ./... -coverprofile=coverage.out -covermode=atomic


test-race :
	@echo "excecuting with race..."
	@go test -v -count=1 -race ./... -coverprofile=coverage.out -covermode=atomic

test-coverage: test
	@echo "Excecuting coverage with report (remember to clean)..."
	@go tool cover -html=coverage.out

simple-coverage:
	@echo "Excecuting coverage in situ..."
	@go tool cover -func=coverage.out | tail -n 1

docker-up:
	@echo "Starting docker containers..."
	@docker compose up -d

docker-down:
	@echo "Stopping docker containers..."
	@docker compose down

clean:
	@echo "Cleaning autogenerated files..."
	@rm -f coverage.out
